name: Login to ECR
description: Login to  ECR
branding:
  color: orange
  icon: corner-right-up
inputs:
  role-to-assume:
    description: role to access AWS
    required: true
  aws-region:
    description: aws region
    default: us-east-1
    required: false
  role-session-name:
    description: AWS role session name
    required: false
  
outputs:
  registry:
    value: ${{ steps.ecr.outputs.registry }}
    description: ECR host

runs:
  using: composite
  steps:
  -
    name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: ${{ inputs.role-to-assume }}
      role-session-name: ${{ inputs.role-session-name }}
      aws-region: ${{ inputs.aws-region }}
  -
    name: Login to Amazon ECR
    id: ecr
    uses: aws-actions/amazon-ecr-login@v2
    with:
      mask-password: true

