name: Push ECR
description: Push to ECR
branding:
  color: red
  icon: upload
inputs:
  role-to-assume:
    description: role to access AWS
    required: true
  aws-region:
    description: aws region
    default: us-east-1
    required: false
  role-session-name:
    description: AWS role session name
    required: false
  image-name:
    description: Image to push
    required: true
    
outputs:
  registry:
    value: ${{ steps.ecr.outputs.registry }}
    description: ECR host

runs:
  using: composite
  steps:
  -
    name: Login to ECR
    uses: comet-ml/gha-tools/ecr/login@main
    id: ecr
    with:
      role-to-assume: ${{ inputs.role-to-assume }}
      role-session-name: ${{ inputs.role-session-name }}
      aws-region: ${{ inputs.aws-region }}
  - 
    name: Set tags and push
    shell: bash
    run: |
      docker tag ${{ inputs.image-name }} ${{ steps.ecr.outputs.registry }}/${{ inputs.image-name }}

