name: Get Latest Tag
description: Get latest parent/global tag for commit
inputs:
  do-checkout:
    description: do repo checkout
    default: 'true'
    required: false
  default-tag:
    description: set tag if nothing found
    default: '0.0.0'
    required: false
  do-tag-create:
    description: create new tag
    default: 'false'
    required: false
  increment:
    description: increment step
    default: '1'
    required: false
outputs:
  tag:
    value: ${{ steps.get-tag.outputs.tag}}
    description: latest tag

runs:
  using: composite
  steps:
    - name: do checkout
      if: inputs.do-checkout != 'false'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        sparse-checkout: |
          version.txt

    - name: get tag
      id: get-tag
      shell: bash
      run: |
        # get latest tag
        set -x +e
        # getting latest parent taggithub.event.number
        eval "$(git describe --tags --long --first-parent ${GITHUB_SHA} | sed -r 's/^(v?([0-9]+))(\.([0-9]+)(\.([0-9]+)(.*))?)?-([0-9]+)-[0-9a-h]+$/parent_prefix=\1;parent_major=\2;parent_minor=\4;parent_patch=\6;parent_extra=\7;parent_tag_offset=\8;/')"
        echo "offset ${parent_tag_offset}"
        if [ $? -ne 0 ] ; then
          tag_matcher=
        else
          tag_matcher=$parent_prefix
          if [ -n $parent_minor ] ; then
            tag_matcher="${tag_matcher}.${parent_minor}"
          fi
          if [ -n $parent_patch ] ; then
            tag_matcher="${tag_matcher}."
          fi
        fi
        # get the latest tag
        eval "$(git describe --tags --long --match="${tag_matcher}*" HEAD | sed -r 's/^(v?([0-9]+))(\.([0-9]+)(\.([0-9]+)(.*))?)?-([0-9]+)-[0-9a-h]+$/tag_prefix=\1;tag_major=\2;tag_minor=\4;tag_patch=\6;tag_extra=\7;tag_offset=\8;/')"
        if [ -z "${tag_major}" ] ; then
          new_tag="${{ inputs.default-tag }}"
        else
          # tag found, we need increase patch
          new_tag="${tag_prefix}"
          if [ -z "${tag_minor}" ] ; then
            new_tag="${tag_prefix}.0"
          elif [ -z "${tag_patch}" ] ; then
            new_tag="${tah_prefix}.$(( tag_minor + ${{ inputs.increment }} ))"
          else
            new_tag="${tag_prefix}.${tag_minor}.$(( tag_patch + ${{ inputs.increment }} ))"
          fi
        fi
        echo "tag=${new_tag}" | tee -a "${GITHUB_OUTPUT}"

    - name: create tag
      if: inputs.do-tag-create != 'false'
      shell: bash
      env:
        TAG: ${{ steps.get-tag.outputs.tag}}
      run: |
        # do tag create
        set -x
        git tag ${TAG}
        git push origin ${TAG}
